# Generated by Django 6.0.2 on 2026-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('year_level', models.IntegerField()),
                ('relationship_status', models.CharField(choices=[('Single', 'Single'), ('In a Relationship', 'In a Relationship'), ('Married', 'Married')], default='Single', max_length=20)),
            ],
        ),
    ]
